### PR TITLE
Add julia tutorial basic

### LINKED ISSUE #1: Basic Julia tutorials

### LINKED ISSUE #7: Julia tutorial: Plots, Transducers, etc.

### LINKED ISSUE #8: Julia tutorial: FlightSims, UnPack, ComponentArrays

### PR DESCRIPTION
**Pull request by JinraeKim**
Resolve #1, #7, #8.
@Youngjun-Lee-FDCL hope this helps you.

### CODE REVIEW

**Comment by Youngjun-Lee-FDCL** [comment]
all confirmed

**Comment by JinraeKim** [comment]
> all confirmed

You need to "review" this PR to merge it into the protected branch `main`
although the administrator (me) can force it to be merged.

For example,
image

**Review by Youngjun-Lee-FDCL — APPROVED** [review]
Thank you for your basic julia code!

**Comment by Youngjun-Lee-FDCL** [comment]
The reaction speed is so fast!

**Comment by JinraeKim** [comment]
> The reaction speed is so fast!

lol what a coincidence :)

**Pull request merged**
